### ISSUE TITLE
Форма не открывается в дизайнере PascalABC.NET

### ISSUE THREAD

**Issue by avkw1** [Kicshikxo/Pascal-tetris#1]
Возможно, не хватает файла .fmabc?
Проверялось на версии PascalABC.NET 3.9.0
Подскажите, как открыть форму в дизайнере.

**Comment by Kicshikxo** [comment]
Спасибо за интерес к проекту! Действительно, не загрузил файл .fmabc, думал что он не нужен, сейчас всё загрузил
